// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/codeharmony/work/ReactNative/coffeeMartApp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/codeharmony/work/ReactNative/coffeeMartApp/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('AwesomeProjectOne', appParameters);
});
require('/Users/codeharmony/work/ReactNative/coffeeMartApp/index.js');